Fixing elastic curator, elasticsearch, fluentd
feature-creeps/observability-workshop pull request #144
Opened 2023-10-05 14:28 UTC by lieberlois

2023-10-05 17:05 UTC, BlacCello requested changes

2023-10-05 17:05 UTC, BlacCello commented on stack/kubernetes/tools/logging/fluentd.yaml
> +podSecurityPolicy:
Please also adjust `local/kubernetes/tools/logging/fluentd.yaml` 
Side note: I don't want to have all those files replicated, but currently we have this setup...

2023-10-05 17:05 UTC, BlacCello commented on stack/kubernetes/24_deploy_logging.sh
> +FLUENTD_VERSION="0.4.3"
Please adjust `local/kubernetes/22b_deploy_logging_elastic.sh` as well.

2023-10-05 17:05 UTC, BlacCello commented on stack/kubernetes/tools/logging/curator.yaml
> +image:
local file has to be adjusted as well

2023-10-05 17:05 UTC, BlacCello commented on stack/kubernetes/tools/logging/elasticsearch.yaml
>  ---
local file has to be adjusted as well

2023-10-05 20:45 UTC, lieberlois commented on stack/kubernetes/tools/logging/fluentd.yaml
> +podSecurityPolicy:
I added the new prometheus source, the PSP was already set to disabled in the local file.

2023-10-05 20:45 UTC, lieberlois commented on stack/kubernetes/tools/logging/elasticsearch.yaml
>  ---
Done :) i set the RAM requests to 1 Gi (JVM has 512 MB, which is recommended for Elastic / OpenSearch - 50 % of available RAM for the JVM memory)

2023-10-05 20:45 UTC, lieberlois commented on stack/kubernetes/tools/logging/curator.yaml
> +image:
Done.

2023-10-05 20:47 UTC, lieberlois commented on stack/kubernetes/24_deploy_logging.sh
> +FLUENTD_VERSION="0.4.3"
Done

2023-10-09 06:25 UTC, BlacCello approved these changes

2023-10-09 06:25 UTC, merged